#!/bin/bash

python recall_precision.py url .. 1 -save &
python recall_precision.py url .. 10 -save &
python recall_precision.py genomes .. 1 -save &
python recall_precision.py genomes .. 10 -save &
python recall_precision.py proteomes .. 1 -save &
python recall_precision.py proteomes .. 10 -save &

python recall_time.py url .. R1@1 -save &
python recall_time.py url .. R1@10 -save &
python recall_time.py url .. R1@100 -save &
python recall_time.py url .. R10@10 -save &
python recall_time.py url .. R10@100 -save &
python recall_time.py url .. R100@100 -save &

python recall_time.py genomes .. R1@1 -save &
python recall_time.py genomes .. R1@10 -save &
python recall_time.py genomes .. R1@100 -save &
python recall_time.py genomes .. R10@10 -save &
python recall_time.py genomes .. R10@100 -save &
python recall_time.py genomes .. R100@100 -save &

python recall_time.py proteomes .. R1@1 -save &
python recall_time.py proteomes .. R1@10 -save &
python recall_time.py proteomes .. R1@100 -save &
python recall_time.py proteomes .. R10@10 -save &
python recall_time.py proteomes .. R10@100 -save &
python recall_time.py proteomes .. R100@100 -save &

wait

